name: Java CI
on: 
  push:
    paths-ignore: 
      - 'docs/**'
      - 'LICENSE'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - run: mvn -B clean compile test-compile
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B test
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  check:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B checkstyle:check pmd:check spotbugs:check
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B jacoco:report
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  sonar:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B sonar:sonar -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B jar:jar javadoc:jar source:jar-no-fork
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  site:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - run: mvn -B site
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: site
        path: target
