name: Java CI
on: 
  push:
    branches-ignore: gh-pages
    paths-ignore: 
      - 'docs/**'
      - '.editorconfig'
      - 'LICENSE'
      - 'README.md'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - run: mvn -B clean compile test-compile
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B test
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B checkstyle:check pmd:check spotbugs:check
  coverage:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B jacoco:report
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  sonar:
    runs-on: ubuntu-latest
    needs: coverage
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B sonar:sonar -Dsonar.login="${{ secrets.SONAR_TOKEN }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B jar:jar javadoc:jar source:jar-no-fork
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  publish:
    runs-on: ubuntu-latest
    needs: package
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B install
  site:
    runs-on: ubuntu-latest
    needs: [lint, coverage]
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ~/.m2
        key: ${{ runner.os }}-maven-${{ hashFiles('pom.xml') }}
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: mvn -B site
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: target
        path: target
  pages:
    runs-on: ubuntu-latest
    needs: site
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: gh-pages
    - name: Set up Java
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Download artifact
      uses: actions/download-artifact@v1
      with:
        name: target
    - run: |
        rm -Rf apidocs css images jacoco *.html 
        mv target/site .
        git config --local user.name "GitHub Actions"
        git config --local user.email "actions@github.com"
        git add site
        git commit -m "Pages"
    - name: Push changes
      uses: ad-m/github-push-action@v0.5.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
